const flagData = [

{name:'Andorra', 	continent:'EU', top: , left: },
{name:'UAE', 		continent:'AS', top: , left: },
{name:'Afghanistan', continent:'AS', top: , left: },
{name:'Antigua and Barbuda', continent:'AM', top: , left: },
{name:'Anguilla', continent:'DEP', top: , left: },
{name:'Armenia', continent:'AS', top: , left: },
{name:'Netherlands Antilles', continent:'DEP', top: , left: },
{name:'Angola', continent:'AF', top: , left: },
{name:'Antarctica', continent:'DEP', top: , left: },
{name:'Argentina', continent:'AM', top: , left: },
{name:'American Samoa', continent:'DEP', top: , left: },
{name:'Austria', continent:'EU', top: , left: },
{name:'Australia', continent:'AO', top: , left: },
{name:'Aruba', continent:'DEP', top: , left: },
{name:'Azerbaijan', continent:'AS', top: , left: },
{name:'Bosnia and Herzegovina', continent:'EU', top: , left: },
{name:'Barbados', continent:'AM', top: , left: },
{name:'Bangladesh', continent:'AS', top: , left: },
{name:'Belgium', continent:'EU', top: , left: },
{name:'Burkina Faso', continent:'AF', top: , left: },
{name:'Bulgaria', continent:'EU', top: , left: },
{name:'Bahrain', continent:'AS', top: , left: },
{name:'Burundi', continent:'AF', top: , left: },
{name:'Benin', continent:'AF', top: , left: },
{name:'Bermuda', continent:'DEP', top: , left: },
{name:'Brunei', continent:'AS', top: , left: },
{name:'Bolivia', continent:'AM', top: , left: },
{name:'Brazil', continent:'AM', top: , left: },
{name:'The Bahamas', continent:'AM', top: , left: },
{name:'Bhutan', continent:'AS', top: , left: },
{name:'Bouvet Island', continent:'DEP', top: , left: },
{name:'Botswana', continent:'AF', top: , left: },
{name:'Belarus', continent:'EU', top: , left: },
{name:'Belize', continent:'AM', top: , left: },
{name:'Canada', continent:'AM', top: , left: },
{name:'Cocos Islands', continent:'DEP', top: , left: },
{name:'DR Congo', continent:'AF', top: , left: },
{name:'Central African Republic', continent:'AF', top: , left: },
{name:'Congo', continent:'AF', top: , left: },
{name:'Switzerland', continent:'EU', top: , left: },
{name:'Ivory Coast', continent:'AF', top: , left: },
{name:'Cook Islands', continent:'DEP', top: , left: },
{name:'Chile', continent:'AM', top: , left: },
{name:'Cameroon', continent:'AF', top: , left: },
{name:'China', continent:'AS', top: , left: },
{name:'Colombia', continent:'AM', top: , left: },
{name:'Costa Rica', continent:'AM', top: , left: },
{name:'Cuba', continent:'AM', top: , left: },
{name:'Cape Verde', continent:'AF', top: , left: },
{name:'Christmas Island', continent:'DEP', top: , left: },
{name:'Cyprus', continent:'EU', top: , left: },
{name:'Czech Republic', continent:'EU', top: , left: },
{name:'Germany', continent:'EU', top: , left: },
{name:'Djibouti', continent:'AF', top: , left: },
{name:'Denmark', continent:'EU', top: , left: },
{name:'Dominica', continent:'AM', top: , left: },
{name:'Dominican Republic', continent:'', top: , left: },
{name:'Algeria', continent:'AF', top: , left: },
{name:'Ecuador', continent:'AM', top: , left: },
{name:'Estonia', continent:'EU', top: , left: },
{name:'Egypt', continent:'AF', top: , left: },
{name:'Western Sahara', continent:'DEP', top: , left: },
{name:'Eritrea', continent:'AF', top: , left: },
{name:'Spain', continent:'EU', top: , left: },
{name:'Ethiopia', continent:'AF', top: , left: },
{name:'Finland', continent:'EU', top: , left: },
{name:'Fiji', continent:'AO', top: , left: },
{name:'Ghana', continent:'AF', top: , left: },
{name:'Gibraltar', continent:'DEP', top: , left: },
{name:'Greenland', continent:'DEP', top: , left: },
{name:'Gambia', continent:'AF', top: , left: },
{name:'Guinea', continent:'AF', top: , left: },
{name:'Equatorial Guinea', continent:'AF', top: , left: },
{name:'Greece', continent:'EU', top: , left: },
{name:'South Georgia & Sandwich', continent:'DEP', top: , left: },
{name:'Guatemala', continent:'AM', top: , left: },
{name:'Guam', continent:'DEP', top: , left: },
{name:'Guinea-Bissau', continent:'AF', top: , left: },
{name:'Guyana', continent:'AM', top: , left: },
{name:'Hong Kong', continent:'DEP', top: , left: },
{name:'Heard & McDonald Islands', continent:'DEP', top: , left: },
{name:'Honduras', continent:'AM', top: , left: },
{name:'Croatia', continent:'EU', top: , left: },
{name:'Haiti', continent:'AM', top: , left: },
{name:'Hungary', continent:'EU', top: , left: },
{name:'Indonesia', continent:'AS', top: , left: },
{name:'Ireland', continent:'EU', top: , left: },
{name:'Israel', continent:'AS', top: , left: },
{name:'Isle of Man', continent:'DEP', top: , left: },
{name:'India', continent:'AS', top: , left: },
{name:'British Indian Ocean Ter.', continent:'DEP', top: , left: },
{name:'Iraq', continent:'AS', top: , left: },
{name:'Iran', continent:'AS', top: , left: },
{name:'Iceland', continent:'EU', top: , left: },
{name:'Italy', continent:'EU', top: , left: },
{name:'Jersey', continent:'DEP', top: , left: },
{name:'Jamaica', continent:'AM', top: , left: },
{name:'Jordan', continent:'AS', top: , left: },
{name:'Japan', continent:'AS', top: , left: },
{name:'Kenya', continent:'AF', top: , left: },
{name:'Kyrgyztan', continent:'AS', top: , left: },
{name:'Cambodia', continent:'AS', top: , left: },
{name:'Kiribati', continent:'AO', top: , left: },
{name:'Comoros', continent:'AF', top: , left: },
{name:'Saint Kitts & Nevis', continent:'AM', top: , left: },
{name:'North Korea', continent:'AS', top: , left: },
{name:'South Korea', continent:'AS', top: , left: },
{name:'Kuwait', continent:'AS', top: , left: },
{name:'Cayman Islands', continent:'DEP', top: , left: },
{name:'Kazakhstan', continent:'AS', top: , left: },
{name:'Laos', continent:'AS', top: , left: },
{name:'Lebanon', continent:'AS', top: , left: },
{name:'Saint Lucia', continent:'AM', top: , left: },
{name:'Lichtenstein', continent:'EU', top: , left: },
{name:'Sri Lanka', continent:'AS', top: , left: },
{name:'Liberia', continent:'AF', top: , left: },
{name:'Lesotho', continent:'AF', top: , left: },
{name:'Lithuania', continent:'EU', top: , left: },
{name:'Luxembourg', continent:'EU', top: , left: },
{name:'Latvia', continent:'EU', top: , left: },
{name:'Libya', continent:'AF', top: , left: },
{name:'Morocco', continent:'AF', top: , left: },
{name:'Monaco', continent:'EU', top: , left: },
{name:'Moldova', continent:'EU', top: , left: },
{name:'Montenegro', continent:'EU', top: , left: },
{name:'Madagascar', continent:'AFF', top: , left: },
{name:'Marshall Islands', continent:'AO', top: , left: },
{name:'Macedonia', continent:'EU', top: , left: },
{name:'Mali', continent:'AF', top: , left: },
{name:'Burma', continent:'AS', top: , left: },
{name:'Mongolia', continent:'AS', top: , left: },
{name:'Macau', continent:'DEP', top: , left: },
{name:'Northern Mariana', continent:'DEP', top: , left: },
{name:'Mauritania', continent:'AF', top: , left: },
{name:'Montserrat', continent:'DEP', top: , left: },
{name:'Malta', continent:'EU', top: , left: },
{name:'Mauritius', continent:'AF', top: , left: },
{name:'Maldives', continent:'AS', top: , left: },
{name:'Malawi', continent:'AF', top: , left: },
{name:'Mexico', continent:'AM', top: , left: },
{name:'Malaysia', continent:'AS', top: , left: },
{name:'Mozambique', continent:'AF', top: , left: },
{name:'Namibia', continent:'AF', top: , left: },
{name:'New Caledonia', continent:'DEP', top: , left: },
{name:'Niger', continent:'AF', top: , left: },
{name:'Norfolk Island', continent:'DEP', top: , left: },
{name:'Nigeria', continent:'AF', top: , left: },
{name:'Nicaragua', continent:'AM', top: , left: },
{name:'Netherlands', continent:'EU', top: , left: },
{name:'Norway', continent:'EU', top: , left: },
{name:'Nauru', continent:'AO', top: , left: },
{name:'Niue', continent:'DEP', top: , left: },
{name:'New Zealand', continent:'AO', top: , left: },
{name:'Pictairn', continent:'DEP', top: , left: },
{name:'Puerto Rico', continent:'DEP', top: , left: },
{name:'Gaza Strip', continent:'DEP', top: , left: },
{name:'Portugal', continent:'EU', top: , left: },
{name:'Palau', continent:'AO', top: , left: },
{name:'Paraguay', continent:'AM', top: , left: },
{name:'Qatar', continent:'AS', top: , left: },
{name:'Romania', continent:'EU', top: , left: },
{name:'Serbia', continent:'EU', top: , left: },
{name:'Russia', continent:'EU', top: , left: },
{name:'Rwanda', continent:'AF', top: , left: },
{name:'Saudi Arabia', continent:'AS', top: , left: },
{name:'Solomon Islands', continent:'AO', top: , left: },
{name:'Seychelles', continent:'AS', top: , left: },
{name:'Sudan', continent:'AF', top: , left: },
{name:'Sweden', continent:'EU', top: , left: },
{name:'Singapore', continent:'AS', top: , left: },
{name:'Saint Helena', continent:'DEP', top: , left: },
{name:'Slovenia', continent:'EU', top: , left: },
{name:'Svalbard', continent:'DEP', top: , left: },
{name:'Slovakia', continent:'EU', top: , left: },
{name:'Sierra Leone', continent:'AF', top: , left: },
{name:'San Marino', continent:'EU', top: , left: },
{name:'Senegal', continent:'AF', top: , left: },
{name:'Somalia', continent:'AF', top: , left: },
{name:'Suriname', continent:'AM', top: , left: },
{name:'Sao Tome & Principe', continent:'AF', top: , left: },
{name:'Salvador', continent:'AM', top: , left: },
{name:'Syria', continent:'AS', top: , left: },
{name:'Swaziland', continent:'AF', top: , left: },
{name:'Turks and Caicos', continent:'DEP', top: , left: },
{name:'Chad', continent:'AF', top: , left: },
{name:'French Southern & Antarctic L.', continent:'DEP', top: , left: },
{name:'Togo', continent:'AF', top: , left: },
{name:'Thailand', continent:'AS', top: , left: },
{name:'Tajikistan', continent:'AS', top: , left: },
{name:'Tokelau', continent:'DEP', top: , left: },
{name:'Timor', continent:'AO', top: , left: },
{name:'Turkmenistan', continent:'AS', top: , left: },
{name:'Tunisia', continent:'AF', top: , left: },
{name:'Tonga', continent:'AO', top: , left: },
{name:'Turkey', continent:'EU', top: , left: },
{name:'Trinidad & Tobago', continent:'AM', top: , left: },
{name:'Tuvalu', continent:'AO', top: , left: },
{name:'Taiwan', continent:'DEP', top: , left: },
{name:'Tanzania', continent:'AF', top: , left: },
{name:'Ukraine', continent:'EU', top: , left: },
{name:'Uganda', continent:'AF', top: , left: },
{name:'United States', continent:'AM', top: , left: },
{name:'Uruguay', continent:'AM', top: , left: },
{name:'Uzbekistan', continent:'AS', top: , left: },
{name:'Vatican', continent:'EU', top: , left: },
{name:'St. Vincent & Grenadines', continent:'AM', top: , left: },
{name:'Venezuela', continent:'AM', top: , left: },
{name:'British Virgin Islands', continent:'DEP', top: , left: },
{name:'Virgin Islands', continent:'DEP', top: , left: },
{name:'Vietnam', continent:'AS', top: , left: },
{name:'Vanuatu', continent:'AO', top: , left: },
{name:'Wallis & Futuna', continent:'DEP', top: , left: },
{name:'Samoa', continent:'AO', top: , left: },
{name:'Yemen', continent:'AS', top: , left: },
{name:'Mayotte', continent:'DEP', top: , left: },
{name:'South Africa', continent:'AF', top: , left: },
{name:'Zambia', continent:'AF', top: , left: },
{name:'Zimbabwe', continent:'AF', top: , left: },
{name:'Nepal', continent:'AS', top: , left: },
{name:'Albania', continent:'EU', top: , left: }

];